import { Product, Testimonial, AtelierLocation, QuizQuestion, VIPBenefit } from "./types";

export const PRODUCTS: Product[] = [

  // ═══════════════════════════════════════
  // SUITS — 10 products
  // ═══════════════════════════════════════
  {
    id: "prod-s1",
    name: "Aureum Savile Bespoke Tuxedo",
    description: "Handcrafted Savile Row midnight black wool-cashmere tuxedo with silk-satin peak lapels and 24k gold-thread pinstripes.",
    price: 4800,
    image: "https://images.unsplash.com/photo-1617137968427-85924c800a22?auto=format&fit=crop&q=80&w=800",
    category: "Suits",
    subCategory: "Evening Wear",
    rating: 5.0,
    featured: true,
    optionsLabel: "Fitted Size",
    options: ["38R (Slim)", "40R (Regular)", "42R (Regular)", "42L (Athletic)", "44R (Bespoke)"],
    fullDescription: "Designed for the modern connoisseur, this bespoke tuxedo is meticulously sculpted from premium super-150s midnight black wool blended with fine Himalayan cashmere. Features functional gold-plated buttonholes, structured double shoulders, full silk-satin inner canvas, and hand-stitched 24k gold pinstripes that capture the light as you move.",
    highlights: ["Super 150's Wool & Pure Himalayan Cashmere", "Hand-stitched 24k gold-wrapped metallic threading", "Traditional English tailors structured silhouette", "Full internal horsehair canvas construction"],
    specifications: { "Material": "85% Virgin Wool, 12% Cashmere, 3% Gilded Silk Thread", "Canvas": "Full Heritage Floating Horsehair", "Origin": "Savile Row Atelier, London", "Care": "Professional Museum-Grade Dry Clean Only" }
  },
  {
    id: "prod-s2",
    name: "Obsidian Velvet Bespoke Blazer",
    description: "An elegant heavyweight plush Italian velvet double-breasted blazer with signature custom polished-brass military buttons.",
    price: 3400,
    image: "https://images.unsplash.com/photo-1594938298603-c8148c4dae35?auto=format&fit=crop&q=80&w=800",
    category: "Suits",
    subCategory: "Separates",
    rating: 4.8,
    featured: true,
    optionsLabel: "Chest Size",
    options: ["38 Slim", "40 Regular", "42 Regular", "44 Tall"],
    fullDescription: "Inspired by old-world Milanese salons, this heavy velvet blazer is crafted from exceptional Italian velvet. Highly structured, the rich pile ensures a deep obsidian black hue that is unmatched. Adorned with gold crest brass buttons hand-forged in a century-old atelier.",
    highlights: ["100% fine ribbed cotton Italian velvet", "Hand-polished solid brass embossed crest buttons", "Flattering tailored double-breasted fit", "Signature silk-jacquard golden paisley lining"],
    specifications: { "Fabric": "100% Cotton Velvet (Como, Italy)", "Buttons": "Forged Brass with 24k gold flash finish", "Lining": "100% Mulberry Silk Jacquard", "Lapel": "Wide Peak, Hand-Rolled" }
  },
  {
    id: "prod-s3",
    name: "Imperial Chalk-Stripe Three-Piece",
    description: "A commanding charcoal grey chalk-stripe three-piece suit, hand-tailored from super-180s Merino wool with a matching waistcoat.",
    price: 5200,
    image: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&q=80&w=800",
    category: "Suits",
    subCategory: "Business",
    rating: 4.9,
    featured: true,
    optionsLabel: "Fitted Size",
    options: ["38R", "40R", "42R", "44R", "46R (Bespoke)"],
    fullDescription: "Power dressing elevated to art form. Cut from exclusive English super-180s Merino wool in deep charcoal with subtle white chalk striping, this three-piece commands every boardroom and black-tie dinner. The matching single-breasted waistcoat features six solid gold buttons and an adjustable satin back.",
    highlights: ["Super 180's English Merino Wool", "Full floating horsehair canvas chest piece", "Hand-padded peaked lapels with silk thread buttonholes", "Matching 6-button waistcoat with satin adjustable back"],
    specifications: { "Fabric": "Super 180s Merino Wool (Bradford, UK)", "Lining": "Bemberg Cupro + Silk Chest", "Buttons": "Solid Horn with Gold Inlay", "Origin": "Huntsman & Sons, Savile Row" }
  },
  {
    id: "prod-s4",
    name: "Midnight Navy Double-Breasted Suit",
    description: "Rich midnight navy pure wool double-breasted suit with peak lapels, hand-stitched working buttonholes and mother-of-pearl buttons.",
    price: 3900,
    image: "https://images.unsplash.com/photo-1560243563-062bfc001d68?auto=format&fit=crop&q=80&w=800",
    category: "Suits",
    subCategory: "Business",
    rating: 4.8,
    featured: false,
    optionsLabel: "Fitted Size",
    options: ["38R Slim", "40R Regular", "42R Regular", "44R Tall"],
    fullDescription: "The double-breasted suit in midnight navy is the ultimate statement of refined confidence. Woven in a proprietary 140s wool from a historic Yorkshire mill, this suit is distinguished by its bold 6x2 button configuration, flared peaked lapels, and hand-stitched functional surgeon cuffs.",
    highlights: ["Super 140s Yorkshire wool in midnight navy", "6x2 double-breasted bold peak lapel configuration", "Working surgeon's cuffs with 4 hand-finished buttons", "Full-length mirror silk lining in champagne gold"],
    specifications: { "Fabric": "Super 140s Wool (Yorkshire, UK)", "Lining": "100% Pure Silk Charmeuse", "Buttons": "Premium Mother of Pearl", "Fit": "Structured Bespoke Silhouette" }
  },
  {
    id: "prod-s5",
    name: "Ivory Dinner Jacket & Trouser Set",
    description: "A rare pure ivory grosgrain-lapelled tuxedo jacket with matching flat-front trousers, lined with black silk satin.",
    price: 4200,
    image: "https://images.unsplash.com/photo-1598032895397-b9472444bf93?auto=format&fit=crop&q=80&w=800",
    category: "Suits",
    subCategory: "Evening Wear",
    rating: 4.7,
    featured: false,
    optionsLabel: "Fitted Size",
    options: ["38R", "40R", "42R", "44R"],
    fullDescription: "Conceived for the modern dandy, this ivory dinner jacket captures the spirit of Monte Carlo summers and Cannes evenings. Cut from opulent wool-silk blend in bone-ivory, the jacket features a silk grosgrain shawl lapel, jetted pockets, and a single covered button closure.",
    highlights: ["Ivory wool-silk blend from Scabal Milano", "Black silk grosgrain shawl lapel and pocket trim", "Bespoke jetted pockets with silk facing", "Flat-front matching trousers with double silk braid"],
    specifications: { "Fabric": "60% Wool, 40% Silk — Scabal Milano", "Lapel": "Shawl Collar, Grosgrain Silk", "Lining": "Black Charmeuse Pure Silk", "Trousers": "Double Black Silk Braid Seam" }
  },
  {
    id: "prod-s6",
    name: "Bordeaux Smoking Jacket",
    description: "A sumptuous deep Bordeaux-red quilted silk smoking jacket with black velvet shawl collar and matching sash belt.",
    price: 2800,
    image: "https://images.unsplash.com/photo-1593030761757-71fae45fa0e7?auto=format&fit=crop&q=80&w=800",
    category: "Suits",
    subCategory: "Evening Wear",
    rating: 4.9,
    featured: false,
    optionsLabel: "Size",
    options: ["S", "M", "L", "XL", "XXL"],
    fullDescription: "Evoking the grand lounges of London's most exclusive private clubs, this Bordeaux smoking jacket is the ultimate garment for private evening entertaining. Crafted from quilted jacquard silk in deep Bordeaux wine, it features a generous black velvet shawl collar and contrasting cuffs.",
    highlights: ["Quilted jacquard pure silk in Bordeaux wine", "Deep-pile black velvet shawl collar and cuffs", "Matching self-tie braided silk sash belt", "Patch pockets lined with cream Dupioni silk"],
    specifications: { "Fabric": "100% Quilted Jacquard Silk", "Collar": "Genuine Black Velvet (Italy)", "Belt": "Braided Silk Cord with Tassel Ends", "Origin": "Anderson & Sheppard, London" }
  },
  {
    id: "prod-s7",
    name: "Heritage Glen Plaid Suit",
    description: "A distinguished glen plaid suit in grey-green tones, woven from heavyweight Scottish tweed with a half-canvas construction.",
    price: 3600,
    image: "https://images.unsplash.com/photo-1511367461989-f85a21fda167?auto=format&fit=crop&q=80&w=800",
    category: "Suits",
    subCategory: "Country",
    rating: 4.7,
    featured: false,
    optionsLabel: "Fitted Size",
    options: ["38R", "40R", "42R", "44R", "46R"],
    fullDescription: "The heritage glen plaid pattern has graced the finest country estates for over a century. This suit is woven at the historic Lovat Mills in Inverness from premium 14oz Scottish wool tweed, presenting a nuanced grey-green pattern with a subtle golden overcheck. Half-canvassed for enduring structure.",
    highlights: ["14oz authentic Scottish Tweed from Lovat Mills, Inverness", "Traditional glen plaid with gold overcheck", "Half-canvas structured chest for lasting shape", "Ticket pocket, patch pockets, and working cuffs"],
    specifications: { "Fabric": "14oz Scottish Tweed (Lovat Mills)", "Canvas": "Half Horsehair Canvas", "Buttons": "Genuine Horn Buttons", "Pockets": "Patch, Ticket & Ticket-Flap" }
  },
  {
    id: "prod-s8",
    name: "White Linen Summer Suit",
    description: "A crisp pure Irish linen summer suit in optical white, softly structured for Riviera elegance and warm-weather formal occasions.",
    price: 2600,
    image: "https://images.unsplash.com/photo-1519353580890-09e8e0b55be4?auto=format&fit=crop&q=80&w=800",
    category: "Suits",
    subCategory: "Summer",
    rating: 4.6,
    featured: false,
    optionsLabel: "Fitted Size",
    options: ["38R Slim", "40R Regular", "42R Regular", "44R"],
    fullDescription: "The white linen suit is summer's ultimate sartorial statement. Woven from the finest pure Irish linen in cool optical white with a subtle loose weave that allows maximum breathability, this suit is softly structured with a single-button closure and natural-shoulder silhouette.",
    highlights: ["Pure Irish linen, 280g natural cool weave", "Soft unstructured shoulder with single chest dart", "Surgeon cuffs with genuine mother-of-pearl buttons", "Contrasting midnight navy lining for surprise reveal"],
    specifications: { "Fabric": "100% Pure Irish Linen (280gsm)", "Lining": "100% Cotton Voile (Unlined Body)", "Buttons": "Natural Mother of Pearl", "Origin": "Naples Sartorial House, Italy" }
  },
  {
    id: "prod-s9",
    name: "Black Tie Silk Barathea Suit",
    description: "The definitive formal black barathea wool-silk suit, hand-padded with grosgrain lapels and a super-fine silk lining.",
    price: 4400,
    image: "https://images.unsplash.com/photo-1623880840102-7df0a9f3545b?auto=format&fit=crop&q=80&w=800",
    category: "Suits",
    subCategory: "Evening Wear",
    rating: 5.0,
    featured: false,
    optionsLabel: "Fitted Size",
    options: ["38R", "40R", "42R", "44R", "46R Bespoke"],
    fullDescription: "Made for the most prestigious black-tie occasions, this barathea suit is cut from a bespoke blend of wool-silk barathea with a pronounced diagonal rib that catches light magnificently. Hand-padded lapels in black grosgrain silk and a jet-black interior lining in pure charmeuse silk complete the picture.",
    highlights: ["Wool-silk barathea with diagonal weave light-catch", "Hand-padded grosgrain silk lapels — notch or peak option", "Four working buttons on surgeon's cuffs", "Jet-black 100% charmeuse silk full lining"],
    specifications: { "Fabric": "Wool-Silk Barathea (Loro Piana Mill)", "Lapel": "Grosgrain Silk, Hand-Padded", "Lining": "Jet Black Charmeuse Silk", "Origin": "Norton & Sons, Savile Row" }
  },
  {
    id: "prod-s10",
    name: "Camel Overcoat Supreme",
    description: "A breathtaking pure camel hair overcoat with hand-stitched notch lapels, fly front and tortoiseshell horn buttons.",
    price: 3800,
    image: "https://images.unsplash.com/photo-1548454782-15b189d129ab?auto=format&fit=crop&q=80&w=800",
    category: "Suits",
    subCategory: "Outerwear",
    rating: 4.9,
    featured: false,
    optionsLabel: "Size",
    options: ["38R", "40R", "42R", "44R", "46R"],
    fullDescription: "The camel overcoat is the ultimate cold-weather statement of breeding and refinement. Woven from pure first-cut camel hair by the Loro Piana atelier in Italy, this generously cut coat drapes with exceptional elegance. It features a fly-front button closure, hand-stitched lapels, and tortoiseshell horn buttons.",
    highlights: ["Pure first-cut inner camel hair by Loro Piana", "Hand-stitched notch lapels with silk buttonholes", "Fly-front concealed button closure", "Full-length natural horn tortoiseshell buttons"],
    specifications: { "Fabric": "100% First-Cut Camel Hair (Loro Piana)", "Lining": "Champagne Gold Bemberg Cupro", "Buttons": "Natural Tortoiseshell Horn", "Length": "Mid-Calf, Single Vent" }
  },

  // ═══════════════════════════════════════
  // WATCHES — 10 products
  // ═══════════════════════════════════════
  {
    id: "prod-w1",
    name: "The Gilded Legacy Chronograph",
    description: "An exceptional masterpiece timepiece of 18k solid yellow gold casing, skeletonized tourbillon, and obsidian black dial.",
    price: 32000,
    image: "https://images.unsplash.com/photo-1547996160-81dfa63595aa?auto=format&fit=crop&q=80&w=800",
    category: "Watches",
    subCategory: "Complications",
    rating: 4.9,
    featured: true,
    optionsLabel: "Bracelet Type",
    options: ["Solid 18K Yellow Gold (Integrated)", "Obsidian Matte Alligator", "Hand-Finished Black Oysterflex"],
    fullDescription: "The absolute pinnacle of watchmaking craftsmanship. Housing our bespoke mechanical caliber, the Aureum Tourbillon features a visible manual-wind escapement, stunning hand-engraved gold bridges, and water resistance up to 50 meters. Complete with an oyster-black dial accented with real diamond hour markers.",
    highlights: ["Bespoke Swiss Caliber Mechanical Hand-Wound movement", "Solid 18 karat yellow gold case with open-work caseback", "Scratch-resistant anti-reflective double sapphire crystal", "72-hour power reserve with twin mainspring barrels"],
    specifications: { "Case": "Solid 18K Yellow Gold, 41mm Diameter", "Movement": "In-house Caliber A99 Automatic Tourbillon", "Jewels": "31 Synthetic Rubies", "Glass": "Dual Curved Premium Sapphire Crystal" }
  },
  {
    id: "prod-w2",
    name: "Aureum Perpetual Moonphase",
    description: "A rare perpetual calendar moonphase complication in platinum, with a hand-guilloché silver dial and blue sapphire crown.",
    price: 48000,
    image: "https://images.unsplash.com/photo-1524592094714-0f0654e20314?auto=format&fit=crop&q=80&w=800",
    category: "Watches",
    subCategory: "Complications",
    rating: 5.0,
    featured: true,
    optionsLabel: "Strap",
    options: ["Platinum Integrated Bracelet", "Mid-Blue Alligator", "Vintage Cordovan Leather"],
    fullDescription: "Among the most complex watches in our collection, the Perpetual Moonphase requires no date correction until the year 2100. The platinum case houses an in-house caliber with four instantaneous jumping date wheels, retrograde day display, and a stunning enamel moonphase disc depicting constellations in Grand Feu enamel.",
    highlights: ["Perpetual calendar accurate until year 2100", "Grand Feu enamel constellation moonphase disc", "Hand-engine-turned silver guilloché sunburst dial", "Platinum 950 case with sapphire exhibition caseback"],
    specifications: { "Case": "Platinum 950, 42mm", "Movement": "Caliber A-3150 Perpetual Calendar", "Power Reserve": "68 Hours", "Water Resistance": "30m / 3 ATM" }
  },
  {
    id: "prod-w3",
    name: "Royal Obsidian Minute Repeater",
    description: "An ultra-rare acoustic complication — a minute repeater in dark DLC titanium that chimes the hours with cathedral gongs.",
    price: 75000,
    image: "https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?auto=format&fit=crop&q=80&w=800",
    category: "Watches",
    subCategory: "Grand Complications",
    rating: 5.0,
    featured: false,
    optionsLabel: "Case Finish",
    options: ["Full Matte DLC Black Titanium", "Satin DLC with Polished Lugs", "Midnight Blue DLC Titanium"],
    fullDescription: "The minute repeater is the rarest and most difficult acoustic complication in haute horlogerie. Our Royal Obsidian uses two cathedral-pitch titanium gongs attached to the mainplate, activated by a push-slide on the left side of the case. It chimes hours, quarter-hours, and minutes with remarkable tonal clarity.",
    highlights: ["Acoustic minute repeater with cathedral titanium gongs", "DLC-coated grade 5 titanium case (featherlight)", "Skeletonized movement visible through two sapphire crystals", "Produced in editions of maximum 12 pieces per year"],
    specifications: { "Case": "Grade 5 DLC Titanium, 43mm", "Gongs": "Titanium Cathedral Gongs", "Production": "12 pieces per annum", "Movement": "Manual-wind, 21 jewels" }
  },
  {
    id: "prod-w4",
    name: "Meridian World Timer",
    description: "An elegant world timer displaying 24 time zones simultaneously on a 18k rose gold case with hand-painted enamel world map dial.",
    price: 28500,
    image: "https://images.unsplash.com/photo-1612817288484-6f916006741a?auto=format&fit=crop&q=80&w=800",
    category: "Watches",
    subCategory: "Complications",
    rating: 4.8,
    featured: false,
    optionsLabel: "Strap",
    options: ["18K Rose Gold Bracelet", "Havana Brown Alligator", "Midnight Navy Alligator"],
    fullDescription: "For the global citizen who traverses time zones with ease, the Meridian World Timer displays all 24 time zones on a stunning rotating bezel. The centrepiece is a hand-painted Grand Feu enamel world map dial depicting continents in midnight blue and ivory, with gold-inlaid city names around the periphery.",
    highlights: ["24 simultaneous time zones on rotating enamel bezel", "Hand-painted Grand Feu enamel world map dial", "18K rose gold case with integrated crown guards", "Day/night indicator disc for each hemisphere"],
    specifications: { "Case": "18K Rose Gold, 40mm", "Dial": "Grand Feu Enamel (5 firings)", "Movement": "Caliber A-2250 World Timer", "Cities": "24 reference cities on enamel ring" }
  },
  {
    id: "prod-w5",
    name: "Heritage Pocket Watch",
    description: "A magnificent solid gold hunter-case pocket watch with an open-face option, white enamel Roman dial and blued steel hands.",
    price: 18500,
    image: "https://images.unsplash.com/photo-1618220179428-22790b461013?auto=format&fit=crop&q=80&w=800",
    category: "Watches",
    subCategory: "Pocket Watches",
    rating: 4.9,
    featured: false,
    optionsLabel: "Case Style",
    options: ["Full Hunter (Closed Case)", "Half Hunter (Glass Window)", "Open Face Roman Dial"],
    fullDescription: "A celebration of the golden age of horology. Our Heritage Pocket Watch is crafted in solid 18k yellow gold with hand-engraved hunter case featuring our crest motif. The white enamel dial bears elegant Roman numerals with hand-applied gold indices, blued steel Breguet hands, and a small seconds sub-dial at 6 o'clock.",
    highlights: ["Solid 18K yellow gold hand-engraved hunter case", "Pure white Geneva enamel dial with Roman numerals", "Blued Breguet-style steel hands", "Chain attachment in solid 18K gold Albert chain style"],
    specifications: { "Case": "Solid 18K Yellow Gold, 52mm", "Dial": "White Geneva Enamel", "Movement": "Manual wind lever escapement", "Chain": "Solid 18K Gold Albert Chain (40cm)" }
  },
  {
    id: "prod-w6",
    name: "Aureum Skeleton Automatic",
    description: "A stunning architectural skeletonized automatic movement in steel, displaying all 180 micro-components through sapphire front and back.",
    price: 14800,
    image: "https://images.unsplash.com/photo-1585386959984-a4155224a1ad?auto=format&fit=crop&q=80&w=800",
    category: "Watches",
    subCategory: "Skeleton",
    rating: 4.8,
    featured: false,
    optionsLabel: "Strap",
    options: ["Polished Steel Bracelet", "Matte Black Rubber", "Cognac Calf Leather"],
    fullDescription: "Skeletonization taken to its absolute extreme. Every non-essential gram has been machined away from the movement bridges and mainplate, leaving an almost ethereal floating architecture of wheels, springs, and jewels. The movement is finished with Côtes de Genève, bevelled edges and circular perlage.",
    highlights: ["Fully skeletonized movement, 180 visible components", "Sapphire crystal front and caseback — 360° view", "Côtes de Genève, perlage and bevelling throughout", "50m water resistance despite exhibition construction"],
    specifications: { "Case": "Brushed & Polished Steel, 41mm", "Crystal": "Dual Anti-Reflective Sapphire", "Movement": "Caliber A-1050 Skeleton Automatic", "Power Reserve": "48 Hours" }
  },
  {
    id: "prod-w7",
    name: "Black Ceramic Sports Chrono",
    description: "A high-impact black ceramic and titanium sports chronograph with tachymeter, flyback function, and 300m water resistance.",
    price: 9800,
    image: "https://images.unsplash.com/photo-1579586337278-3befd40fd17a?auto=format&fit=crop&q=80&w=800",
    category: "Watches",
    subCategory: "Sport",
    rating: 4.7,
    featured: false,
    optionsLabel: "Strap",
    options: ["Black Ceramic Integrated Bracelet", "Black Vulcanized Rubber", "Carbon Fibre Textile Strap"],
    fullDescription: "Where haute horlogerie meets motorsport precision. The Black Ceramic Sports Chrono is engineered for performance in high-pressure environments, with a monoblock black ceramic case construction, flyback chronograph complication for rapid lap timing, and a solid titanium caseback with helium escape valve.",
    highlights: ["Monoblock scratch-proof black ceramic case construction", "Flyback chronograph — reset without stopping", "300m water resistance with titanium screw-down crown", "Carbon fibre dial with Super-LumiNova plot indices"],
    specifications: { "Case": "Monoblock Black Ceramic, 44mm", "Movement": "Caliber A-7750 Flyback Chronograph", "Water Resistance": "300m / 30 ATM", "Tachymeter": "Inner rotating bezel" }
  },
  {
    id: "prod-w8",
    name: "Platinum Dress Watch Ultra-Thin",
    description: "An impossibly thin 4.2mm platinum dress watch with a cream sunray dial, Roman numerals and a hand-stitched alligator strap.",
    price: 22000,
    image: "https://images.unsplash.com/photo-1516048015710-7a3b4c86be43?auto=format&fit=crop&q=80&w=800",
    category: "Watches",
    subCategory: "Dress",
    rating: 5.0,
    featured: false,
    optionsLabel: "Strap",
    options: ["Platinum Deployment Clasp Alligator", "Ivory Satin Formal Strap", "Chocolate Brown Alligator"],
    fullDescription: "The pinnacle of restraint and refinement. At just 4.2mm thick — barely the width of a stack of four coins — this ultra-thin movement is a technical tour de force. The platinum 950 case is polished to a mirror gloss, housing a cream sunray dial with applied gold Roman numerals and dauphine hands.",
    highlights: ["4.2mm total thickness — thinner than a 5mm case", "Platinum 950 case polished to liquid mirror finish", "Cream sunray dial with applied solid gold Roman numerals", "Hand-stitched glazed alligator strap, Paris stitch"],
    specifications: { "Case": "Platinum 950, 38mm, 4.2mm thick", "Movement": "Ultra-thin Caliber A-8510 (2.1mm)", "Dial": "Cream Sunray, Gold Applied Numerals", "Strap": "Glazed Alligator, Paris Stitch" }
  },
  {
    id: "prod-w9",
    name: "Deep Sea Diver Titanium",
    description: "A professional 1000m diver's watch in grade 5 titanium with a sapphire unidirectional bezel and helium escape valve.",
    price: 8400,
    image: "https://images.unsplash.com/photo-1526045612212-70caf35c14df?auto=format&fit=crop&q=80&w=800",
    category: "Watches",
    subCategory: "Sport",
    rating: 4.6,
    featured: false,
    optionsLabel: "Bezel",
    options: ["Midnight Black Ceramic Bezel", "Deep Ocean Blue Ceramic Bezel", "Gunmetal Grey Bezel"],
    fullDescription: "Built to withstand the crushing pressures of 1000 metres below sea level, our Deep Sea Diver is a technical masterpiece. The grade 5 titanium case is triple-sealed with four gaskets, topped by a domed anti-reflective sapphire crystal rated to 1000m. The luminous dial features tritium gas tubes for permanent illumination.",
    highlights: ["1000m / 100 ATM water resistance certification", "Tritium gas tube permanent illumination — no charging needed", "Grade 5 titanium — strong as steel, 40% lighter", "Sapphire unidirectional timing bezel, ceramic insert"],
    specifications: { "Case": "Grade 5 Titanium, 44mm", "Water Resistance": "1000m / 100 ATM", "Crystal": "Domed Sapphire, 5.5mm thick", "Luminous": "Tritium Gas Tubes (T25)" }
  },
  {
    id: "prod-w10",
    name: "Rose Gold Cloisonné Art Dial",
    description: "A one-of-a-kind collector's piece with a hand-crafted cloisonné enamel dial depicting Japanese cherry blossoms in 18k rose gold.",
    price: 42000,
    image: "https://images.unsplash.com/photo-1623998022290-a8e5a9a32aa1?auto=format&fit=crop&q=80&w=800",
    category: "Watches",
    subCategory: "Art Pieces",
    rating: 5.0,
    featured: false,
    optionsLabel: "Edition",
    options: ["Cherry Blossom (Sakura) — 8 pieces", "Koi Fish (Nishikigoi) — 8 pieces", "Mount Fuji (Fujisan) — 8 pieces"],
    fullDescription: "Among the rarest objects Aureum produces, this cloisonné enamel dial watch is a wearable painting. Each dial takes a miniaturist artisan six weeks to complete, using fine gold wires to create compartments filled with vitreous enamel fired at 800°C repeatedly until the image emerges in jewel-like depth.",
    highlights: ["Cloisonné enamel dial — 6 weeks hand-production per piece", "18K rose gold wires form the miniature compartment walls", "Fired at 800°C minimum 12 times for depth and colour", "Limited to 8 pieces per motif worldwide — certificate included"],
    specifications: { "Case": "18K Rose Gold, 40mm", "Dial": "Grand Feu Cloisonné Enamel", "Production": "8 pieces per motif", "Movement": "Caliber A-2000 Automatic" }
  },

  // ═══════════════════════════════════════
  // LEATHER — 10 products
  // ═══════════════════════════════════════
  {
    id: "prod-l1",
    name: "Grand Tourer Black Calfskin Weekender",
    description: "Prestige matte calfskin travel bag handcrafted with hand-painted gold edges and robust 24k gilded solid brass hardware.",
    price: 2450,
    image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&q=80&w=800",
    category: "Leather",
    subCategory: "Luggage",
    rating: 4.9,
    featured: true,
    optionsLabel: "Hardware Trim",
    options: ["Polished 24K Gold Hardware", "Midnight Black Matte Chrome", "Brushed Rose Gold Hardware"],
    fullDescription: "The ultimate travel companion for private journeys. Hand-sculpted in Florence from a single hide of first-selection Tuscan matte calf leather, this weekender offers beautiful unstructured luxury. Highlighted by 24k gold-plated brass lock zippers and double-stitched reinforcements.",
    highlights: ["Selected full-grain Italian calf leather", "Solid brass zippers and feet triple-plated in 24k gold", "Detachable suede-lined leather shoulder strap", "Interior fully lined with rich waterproof golden monogram jacquard"],
    specifications: { "Dimensions": "52cm L x 28cm H x 24cm W", "Weight": "1.8 kg (Empty)", "Leather": "Tuscan Full-Grain Aniline Calfskin", "Hardware": "Solid Cast Brass with 24K Gold Plating" }
  },
  {
    id: "prod-l2",
    name: "Sovereign Gold-Bar Loafers",
    description: "Finest hand-lasted box-calf leather dress loafers decorated with an elegant 18k gold-finished minimalist logo saddle bar.",
    price: 1350,
    image: "https://images.unsplash.com/photo-1533867617858-e7b97e060509?auto=format&fit=crop&q=80&w=800",
    category: "Leather",
    subCategory: "Footwear",
    rating: 5.0,
    featured: false,
    optionsLabel: "US Shoe Size",
    options: ["8 D(M)", "9 D(M)", "10 D(M)", "11 D(M)", "12 D(M)"],
    fullDescription: "Constructed with a traditional Goodyear welt on a custom elongated last, these sleek loafers seamlessly bridge classic dapper design with contemporary luxury. Features a full leather outer sole, hand-turned stitched seams, and a bespoke sculptural gold-plated brass saddle bar.",
    highlights: ["Select ultra-supple black box-calf French leather", "Hand-finished Goodyear weaved structural sole", "Solid brass gold-electroplated equestrian horsebit saddle", "Padded ultra-comfortable lambskin insole"],
    specifications: { "Upper": "100% French Calfskin Leather", "Sole": "Triple-Layer Veg-Tanned Oak Bark Leather", "Construction": "Goodyear Welted (Recraftable)", "Made In": "Parma Boutique Atelier, Italy" }
  },
  {
    id: "prod-l3",
    name: "Florentine Portfolio & Document Case",
    description: "A hand-stitched vegetable-tanned Florentine leather document portfolio with solid gold zipper pulls and a monogram panel.",
    price: 980,
    image: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&q=80&w=800",
    category: "Leather",
    subCategory: "Small Leather Goods",
    rating: 4.8,
    featured: false,
    optionsLabel: "Monogram",
    options: ["No Monogram", "Gold Blind Emboss (3 initials)", "Gold Foil Stamp (3 initials)"],
    fullDescription: "Every executive meeting deserves an accessory of equal gravitas. This slim document portfolio is hand-constructed in Florence from full-grain vegetable-tanned leather that develops a rich patina over decades of use. The interior features multiple card slots, a document compartment, and a gold pen loop.",
    highlights: ["Full-grain Florentine vegetable-tanned leather", "Hand-saddle-stitched with waxed linen thread", "Solid brass YKK gold zipper with leather pull tab", "10 card slots + 2 document compartments + pen loop"],
    specifications: { "Dimensions": "34cm x 24cm x 2cm", "Leather": "Full-Grain Veg-Tanned (Florence)", "Stitching": "Hand Saddle Stitch, Waxed Linen", "Hardware": "Solid Brass (Gold Finish)" }
  },
  {
    id: "prod-l4",
    name: "Cognac Derby Oxford Shoes",
    description: "A masterwork of English cordwaining — deep cognac calf oxfords on a handmade last with double leather sole and broguing.",
    price: 1680,
    image: "https://images.unsplash.com/photo-1614252369475-531eba835eb1?auto=format&fit=crop&q=80&w=800",
    category: "Leather",
    subCategory: "Footwear",
    rating: 4.9,
    featured: false,
    optionsLabel: "UK Size",
    options: ["7F", "8E", "8F", "9E", "9F", "10E", "10F", "11E"],
    fullDescription: "Hand-welted on a bespoke English last at a Northampton cordwaining house founded in 1887. The upper is cut from a single skin of premium cognac-dyed calf, with a full broguing pattern hand-punched by master craftsmen. The double leather sole is stitched and pegged, not glued — for a lifetime of resoling.",
    highlights: ["Single-skin premium cognac dyed calfskin upper", "Hand-punched full brogue medallion and wing cap", "Double leather sole — stitched and pegged (not glued)", "Recraftable for lifetime ownership at Aureum Atelier"],
    specifications: { "Upper": "Premium English Calfskin, Cognac", "Sole": "Double Leather, Stitched & Pegged", "Construction": "Hand Goodyear Welted", "Last": "H Last — Classic English Width" }
  },
  {
    id: "prod-l5",
    name: "Crocodile Bifold Wallet",
    description: "An ultra-slim wallet in CITES-certified Nile crocodile belly skin with 18k gold corner reinforcements and 8 card slots.",
    price: 2200,
    image: "https://images.unsplash.com/photo-1627123424574-724758594e93?auto=format&fit=crop&q=80&w=800",
    category: "Leather",
    subCategory: "Small Leather Goods",
    rating: 4.9,
    featured: false,
    optionsLabel: "Skin Tone",
    options: ["Cognac Nile Crocodile", "Midnight Black Crocodile", "Chocolate Brown Crocodile"],
    fullDescription: "Among the most exclusive small leather goods in existence. Crafted from CITES-certified Nile crocodile belly skin — the most prized cut for its symmetrical scale pattern — this bifold wallet is hand-stitched with 18k gold wire thread and finished with gold corner plates solid-cast at our Italian atelier.",
    highlights: ["CITES-certified genuine Nile crocodile belly skin", "Hand-stitched with real 18k gold wire thread", "Solid 18k gold corner reinforcement plates", "8 card slots + 2 note compartments, ultra-slim 8mm profile"],
    specifications: { "Exterior": "CITES Certified Nile Crocodile Belly", "Interior": "Nappa Lambskin", "Stitching": "18K Gold Wire Thread", "Dimensions": "11cm x 9cm x 0.8cm (closed)" }
  },
  {
    id: "prod-l6",
    name: "Monogrammed Valet Tray & Cuff Set",
    description: "A supple Napa leather valet tray with suede lining and a matching leather cuff roll, gold monogrammed with your initials.",
    price: 760,
    image: "https://images.unsplash.com/photo-1491553895911-0055eca6402d?auto=format&fit=crop&q=80&w=800",
    category: "Leather",
    subCategory: "Accessories",
    rating: 4.7,
    featured: false,
    optionsLabel: "Monogram",
    options: ["No Monogram", "Gold Foil Initial (1 letter)", "Gold Foil Monogram (3 letters)"],
    fullDescription: "The gentleman's dressing table demands objects of equal quality. This valet tray and cuff roll set are constructed from smooth grain Napa leather in deep black, with a rich midnight suede lining. The cuff roll accommodates 8 pairs of cufflinks in individual suede pouches, with a top zip in gold.",
    highlights: ["Smooth-grain black Napa leather exterior", "Deep midnight suede lining — valet tray and roll", "Cuff roll holds 8 pairs in individual suede pouches", "Gold top zip and gold foil monogram option"],
    specifications: { "Tray": "28cm x 18cm x 4cm", "Cuff Roll": "24cm x 12cm (Rolled)", "Leather": "Smooth Grain Napa", "Lining": "Midnight Merino Suede" }
  },
  {
    id: "prod-l7",
    name: "Ostrich Leather Belt",
    description: "A statement belt in genuine South African ostrich quill leather with a solid 18k gold-plated buckle and leather-backed keeper.",
    price: 890,
    image: "https://images.unsplash.com/photo-1624958723474-76ac8a5e6952?auto=format&fit=crop&q=80&w=800",
    category: "Leather",
    subCategory: "Accessories",
    rating: 4.8,
    featured: false,
    optionsLabel: "Waist Size",
    options: ["32\"", "34\"", "36\"", "38\"", "40\"", "42\""],
    fullDescription: "Instantly recognisable by its distinctive raised quill pattern, genuine South African ostrich leather is among the world's most exclusive leathers. This dress belt is cut 3.5cm wide from the quill centre — the most prized section — and features a solid brass frame buckle triple-plated in 18k yellow gold.",
    highlights: ["Genuine South African quill-centre ostrich leather", "Solid brass frame buckle, 18K triple-plated", "35mm width — appropriate for dress and business", "Leather-backed tongue keeper for a clean finish"],
    specifications: { "Leather": "South African Quill-Centre Ostrich", "Buckle": "Solid Brass, 18K Gold Plated", "Width": "35mm", "Made In": "Florence, Italy" }
  },
  {
    id: "prod-l8",
    name: "Full-Grain Leather Briefcase",
    description: "A structured top-handle briefcase in dark chocolate full-grain leather with combination lock, 15\" laptop sleeve and solid brass feet.",
    price: 1850,
    image: "https://images.unsplash.com/photo-1547949003-9792a18a2601?auto=format&fit=crop&q=80&w=800",
    category: "Leather",
    subCategory: "Luggage",
    rating: 4.8,
    featured: false,
    optionsLabel: "Colour",
    options: ["Dark Chocolate Brown", "Midnight Black", "Tan Cognac"],
    fullDescription: "For the executive who moves between boardrooms and private terminals, this structured briefcase is built to last decades. Cut from heavyweight full-grain dark chocolate leather that develops a rich patina, it features a twin-compartment interior with a padded 15-inch laptop sleeve, and a three-digit combination lock.",
    highlights: ["Heavyweight full-grain leather, 1.4mm thickness", "Three-digit combination lock on main gusset", "Padded 15\" laptop sleeve + document compartment", "Solid brass feet and solid ring-and-post handle attachment"],
    specifications: { "Dimensions": "42cm x 30cm x 12cm", "Leather": "Full-Grain Vegetable Tanned", "Lock": "3-Digit Combination Brass Lock", "Handle": "Top Handle + Detachable Shoulder Strap" }
  },
  {
    id: "prod-l9",
    name: "Stingray Leather Card Holder",
    description: "A razor-slim 4mm card holder in genuine stingray galuchat skin — naturally textured with its signature pearlescent pebble pattern.",
    price: 480,
    image: "https://images.unsplash.com/photo-1616627578682-a3f65a1bb0f0?auto=format&fit=crop&q=80&w=800",
    category: "Leather",
    subCategory: "Small Leather Goods",
    rating: 4.7,
    featured: false,
    optionsLabel: "Colour",
    options: ["Pearl White Stingray", "Shadow Black Stingray", "Ocean Blue Stingray"],
    fullDescription: "Stingray leather — known in the luxury trade as galuchat — is one of the rarest and most durable exotic leathers available. Its naturally occurring calcified pearl-bead texture is unique to each skin. This ultra-slim card holder holds 6 cards plus a slim note section, and will outlast any conventional leather product.",
    highlights: ["Genuine stingray (galuchat) leather — each unique", "Naturally calcified pearl-bead texture, ultra-durable", "Ultra-slim 4mm profile — 6 cards + note section", "Gold-stitched edges with Nappa lambskin interior"],
    specifications: { "Exterior": "Genuine Stingray Galuchat", "Interior": "Nappa Lambskin", "Capacity": "6 cards + note pocket", "Dimensions": "10cm x 7cm x 0.4cm" }
  },
  {
    id: "prod-l10",
    name: "Bespoke Boot — Hand-Welted",
    description: "A hand-welted Chelsea boot in chocolate suede with gold elastic gussets, a leather stacked heel and a hand-burnished toe cap.",
    price: 2100,
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&q=80&w=800",
    category: "Leather",
    subCategory: "Footwear",
    rating: 4.9,
    featured: false,
    optionsLabel: "UK Size",
    options: ["7", "8", "9", "10", "11", "12"],
    fullDescription: "The Chelsea boot elevated to its highest expression. Hand-welted over a custom elongated last by a fifth-generation English bootmaker, this boot features premium chocolate-brown suede with twin elasticated gold woven gussets, a stacked leather block heel, and a hand-burnished toecap in contrasting smooth calf.",
    highlights: ["Premium chocolate suede upper from Pittards, UK", "Twin gold woven elastic gussets (not synthetic)", "Stacked 4-layer vegetable-tanned leather block heel", "Hand-burnished smooth calf toecap — each pair unique"],
    specifications: { "Upper": "Pittards Chocolate Suede (UK)", "Sole": "Leather Blake-Stitched + Rubber Heel Top", "Construction": "Hand Goodyear Welted", "Last": "Bespoke Chelsea Last — Round Toe" }
  },

  // ═══════════════════════════════════════
  // ACCESSORIES — 10 products
  // ═══════════════════════════════════════
  {
    id: "prod-a1",
    name: "Aureum Classic Amber Noir Parfum",
    description: "A highly concentrated enigmatic signature fragrance of absolute rare oud, charred amber wood, dark cocoa, and gold saffron.",
    price: 420,
    image: "https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&q=80&w=800",
    category: "Accessories",
    subCategory: "Fragrance",
    rating: 4.8,
    featured: false,
    optionsLabel: "Concentration Size",
    options: ["100ml (Extrait de Parfum)", "150ml Decanter + Hand Atomizer", "50ml Travel Flacon"],
    fullDescription: "Whispering untold secrets of exotic spice and warm embers, Amber Noir is the ultimate olfactory statement. It opens with luxurious Iranian saffron and rich nutmeg, melting into Middle Eastern Cambodian oud, and settling with premium white musk, patchouli, and raw gold amber crystals.",
    highlights: ["Extraordinary 30% fragrance oil concentration", "Hand-blown heavy crystalline bottle with brass 24k gilded cap", "Unparalleled projection and 14+ hour sillage longevity", "Sourced with rare ethically harvested natural oils"],
    specifications: { "Olfactory Family": "Woody Oriental / Spicy Oud", "Top Notes": "Saffron, Nutmeg, Suede-Leather", "Heart Notes": "Cambodian Oud, Indonesian Patchouli, Cocoa", "Base Notes": "Golden Amber, Madagascar Vanilla, Sandalwood" }
  },
  {
    id: "prod-a2",
    name: "Gilded Aviator Titanium Shades",
    description: "Japanese lightweight titanium gold-plated aviator sunglasses featuring precious deep obsidian polarized mineral lenses.",
    price: 850,
    image: "https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&q=80&w=800",
    category: "Accessories",
    subCategory: "Eyewear",
    rating: 4.7,
    featured: false,
    optionsLabel: "Frame Variant",
    options: ["18K Yellow Gold & Matte Black", "18K Rose Gold & Havanna Acetate", "White Gold & Slate Grey-Polarized"],
    fullDescription: "A glorious reinterpretation of the iconic aviator. Engineered in Fukui, Japan from grade-5 titanium, then dipped in an 18k yellow gold flash bath. The glasses feature hand-carved acetate temples and premium glass polarized lenses featuring gold anti-reflective back coating.",
    highlights: ["Ultra-strong, hyper-lightweight grade 5 Japanese titanium", "18K gold-plated double bridge structural frame", "Mineral glass lenses with supreme UV400 and infrared blocker", "Comes with bespoke gold-stamped calfskin leather case"],
    specifications: { "Frame Type": "Military Aviator Double-Bridge", "Lens Width": "58 mm", "Bridge Width": "14 mm", "Temple Length": "145 mm" }
  },
  {
    id: "prod-a3",
    name: "Empress Silk Scarf & Cufflinks Set",
    description: "A premium set of pure mulberry hand-rolled gold paisley silk pocket square and matching solid initial cufflinks.",
    price: 680,
    image: "https://images.unsplash.com/photo-1598033129183-c4f50c736f10?auto=format&fit=crop&q=80&w=800",
    category: "Accessories",
    subCategory: "Formal Accents",
    rating: 4.9,
    featured: false,
    optionsLabel: "Monogram engraving",
    options: ["None (Standard)", "Insignia Engraving (Free)", "Bespoke Royal Monogram (Allow 5 days)"],
    fullDescription: "Elevate your formal dressing to regal heights. The scarf is hand-woven in Lake Como from 100% thick mulberry silk with hand-rolled contrasting gold margins. The cufflinks are cast in sterling silver plated with 18k yellow gold, featuring a polished black onyx insert.",
    highlights: ["Scarf crafted in 100% heavy 18-momme Como mulberry silk", "Cufflinks cast from sterling silver base with extra-thick 18K gilding", "Genuine AAA-grade deep black natural onyx stone inlays", "Delivered in a lacquered piano-wood presentation box"],
    specifications: { "Scarf Size": "42cm x 42cm (Standard Pocket)", "Metal": "925 Sterling Silver Plated with 18k Gold", "Stone": "Genuine Black Onyx Cabochons", "Origin": "Como (Silk) & Florence (Metal), Italy" }
  },
  {
    id: "prod-a4",
    name: "Midnight Oud Rose Parfum",
    description: "An ethereal fusion of Turkish rose absolute, aged oud wood, and musk for the man who commands a room with his presence alone.",
    price: 520,
    image: "https://images.unsplash.com/photo-1585386959984-a4155224a1ad?auto=format&fit=crop&q=80&w=800",
    category: "Accessories",
    subCategory: "Fragrance",
    rating: 4.9,
    featured: false,
    optionsLabel: "Size",
    options: ["75ml Extrait de Parfum", "100ml Extrait de Parfum", "30ml Travel Vial"],
    fullDescription: "A fragrance of extraordinary emotional depth. Midnight Oud Rose opens with a burst of Ispahan rose absolute — the most prized rose in perfumery — before descending into aged Laotian oud that has been matured for 25 years. The drydown is an intimate, skin-close musk that lasts throughout the next day.",
    highlights: ["Turkish Ispahan rose absolute — 25kg roses per litre", "25-year aged Laotian oud — the rarest grade available", "25% fragrance concentration — extreme tenacity", "Hand-blown Murano glass bottle with 18k gold collar"],
    specifications: { "Olfactory Family": "Floral Oud", "Top Notes": "Turkish Rose Absolute, Pink Pepper", "Heart Notes": "Aged Laotian Oud, Orris Root", "Base Notes": "White Musk, Ambergris, Vetiver" }
  },
  {
    id: "prod-a5",
    name: "Seven-Fold Silk Mogador Tie",
    description: "A luxurious seven-fold Mogador silk tie in midnight navy with gold micro-dot pattern, unlined for supreme drape.",
    price: 340,
    image: "https://images.unsplash.com/photo-1598032895397-b9472444bf93?auto=format&fit=crop&q=80&w=800",
    category: "Accessories",
    subCategory: "Neckwear",
    rating: 4.8,
    featured: false,
    optionsLabel: "Pattern",
    options: ["Navy & Gold Micro-Dot", "Burgundy & Gold Regimental Stripe", "Forest Green & Gold Paisley"],
    fullDescription: "The seven-fold tie is the Rolls-Royce of neckwear — made from a single square of silk folded seven times on itself, with no internal lining. The result is a tie of extraordinary weight, body, and drape that holds a perfect dimple effortlessly. Woven from Mogador ribbed silk in the finest French mill.",
    highlights: ["Seven-fold construction — no internal lining", "Woven in Mogador ribbed silk (France)", "Self-tipped blade — silk continues through the tip", "Hand-stitched bar tack and slip stitch — allows movement"],
    specifications: { "Silk": "Mogador Ribbed Silk, 150cm", "Construction": "Seven-Fold, Unlined", "Width": "8.5cm (Blade)", "Origin": "Maison Charvet, Paris commission" }
  },
  {
    id: "prod-a6",
    name: "Titanium Money Clip & Card Case",
    description: "An aerospace-grade titanium money clip and card case, laser-engraved with the Aureum crest, holding 8 cards in precision-machined slots.",
    price: 420,
    image: "https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?auto=format&fit=crop&q=80&w=800",
    category: "Accessories",
    subCategory: "Small Accessories",
    rating: 4.7,
    featured: false,
    optionsLabel: "Finish",
    options: ["Brushed Titanium", "Polished Mirror Titanium", "PVD Black Titanium"],
    fullDescription: "Machined from a solid billet of grade 5 aerospace titanium, this money clip and card case combination is a study in precision engineering. Eight card slots are machined with 0.1mm tolerances for a tight, rattle-free fit. The spring-tensioned money clip mechanism is rated to 50,000 open-close cycles.",
    highlights: ["Machined from solid grade 5 aerospace titanium billet", "8 precision-machined card slots, 0.1mm tolerance", "Spring-tensioned clip rated to 50,000 cycles", "Laser-engraved Aureum crest on face"],
    specifications: { "Material": "Grade 5 Aerospace Titanium", "Capacity": "8 cards + 10 folded notes", "Weight": "38g", "Machining": "5-Axis CNC, ±0.1mm tolerance" }
  },
  {
    id: "prod-a7",
    name: "Diamond & Onyx Dress Studs Set",
    description: "A formal dress stud set of five pieces — four shirt studs and one waistcoat button — in 18k white gold with black onyx and diamond centres.",
    price: 3800,
    image: "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&q=80&w=800",
    category: "Accessories",
    subCategory: "Formal Accents",
    rating: 5.0,
    featured: false,
    optionsLabel: "Stone Centre",
    options: ["Black Onyx & Diamond Pavé", "Midnight Sapphire & White Diamond", "Pure Diamond Full Pavé"],
    fullDescription: "For the most formal evenings of the social calendar, dress studs of consequence are essential. This five-piece set in 18k white gold features a bezel-set round black onyx centre stone surrounded by a halo of pavé-set brilliant-cut diamonds. Supplied in a silk-lined wooden jewellery case.",
    highlights: ["18K white gold setting — all five pieces matched", "Bezel-set AAA black onyx centre stones", "40 brilliant-cut diamonds totalling 0.60ct (set)", "Presented in a silk-lined burr walnut jewellery case"],
    specifications: { "Metal": "18K White Gold", "Main Stone": "AAA Black Onyx, 8mm", "Diamonds": "0.60ct Total, F/VS1", "Set Contents": "4 shirt studs + 1 waistcoat button" }
  },
  {
    id: "prod-a8",
    name: "Hand-Rolled Pocket Square Collection",
    description: "A curated set of six hand-rolled pure silk pocket squares in rotating seasonal colourways, presented in a lacquer box.",
    price: 480,
    image: "https://images.unsplash.com/photo-1598032895397-b9472444bf93?auto=format&fit=crop&q=80&w=800",
    category: "Accessories",
    subCategory: "Formal Accents",
    rating: 4.8,
    featured: false,
    optionsLabel: "Collection Season",
    options: ["Winter — Navy, Burgundy, Black", "Summer — Ivory, Sage, Sky Blue", "Heritage — All-Gold Classic Set"],
    fullDescription: "Six essential pocket squares, each hand-rolled at the edges by artisans in Como who dedicate their careers to this single craft. Woven from 22-momme silk twill with a lustre weight that folds crisply and maintains its set for hours, each square measures a generous 44 x 44cm for maximum fold versatility.",
    highlights: ["Six 22-momme silk twill pocket squares per set", "Hand-rolled edges — 3mm tight roll, Como artisans", "44cm x 44cm — oversized for versatile folding", "Presented in a black lacquered hinged wooden box"],
    specifications: { "Silk": "22-Momme Silk Twill (Como)", "Size": "44cm x 44cm each", "Edge": "Hand-Rolled 3mm", "Set": "6 pocket squares + lacquer presentation box" }
  },
  {
    id: "prod-a9",
    name: "Cashmere & Silk Scarf — Aureum Signature",
    description: "A sumptuous winter scarf in 70% cashmere and 30% silk, printed with the Aureum signature pattern and hand-fringed at both ends.",
    price: 620,
    image: "https://images.unsplash.com/photo-1520903920243-00d872a2d1c9?auto=format&fit=crop&q=80&w=800",
    category: "Accessories",
    subCategory: "Neckwear",
    rating: 4.9,
    featured: false,
    optionsLabel: "Colour",
    options: ["Midnight Black & Gold", "Camel & Ivory", "Navy & Champagne"],
    fullDescription: "Winter warmth elevated to art form. Woven in Scotland from a blend of grade-A Mongolian cashmere and pure Tussah silk, this generous scarf is printed with a repeat Aureum heraldic pattern in seasonal tones. The hand-knotted fringe at either end is a signature of quality that no machine can replicate.",
    highlights: ["70% Grade-A Mongolian Cashmere, 30% Tussah Silk", "Woven in Scotland at Johnstons of Elgin mill", "Aureum heraldic repeat print in seasonal palette", "Hand-knotted fringe at both ends — 8cm length"],
    specifications: { "Composition": "70% Cashmere, 30% Tussah Silk", "Woven": "Johnstons of Elgin, Scotland", "Dimensions": "190cm x 35cm", "Fringe": "Hand-knotted, 8cm each end" }
  },
  {
    id: "prod-a10",
    name: "Gold Leaf Fountain Pen",
    description: "A limited edition fountain pen crafted from precious resin and 18k solid yellow gold nib, with a gold leaf infused barrel.",
    price: 1800,
    image: "https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?auto=format&fit=crop&q=80&w=800",
    category: "Accessories",
    subCategory: "Writing Instruments",
    rating: 4.9,
    featured: false,
    optionsLabel: "Nib Size",
    options: ["Fine (F)", "Medium (M)", "Broad (B)", "Italic (1.1mm stub)"],
    fullDescription: "Writing elevated to ceremony. This limited fountain pen features a barrel of hand-cast deep obsidian resin with genuine 22k gold leaf flakes suspended within, creating a unique cosmos-like depth in every pen. The solid 18k gold nib is hand-tuned by a nib meister for perfect ink flow and zero feedback.",
    highlights: ["Barrel of hand-cast resin with suspended 22k gold leaf", "Solid 18k yellow gold nib, hand-tuned by nib meister", "Piston-fill mechanism — 2.5ml ink capacity", "Arrives in a silk-cushioned lacquer presentation box"],
    specifications: { "Barrel": "Hand-Cast Resin with 22K Gold Leaf", "Nib": "Solid 18K Yellow Gold", "Filling": "Piston Fill (2.5ml)", "Edition": "150 pieces per nib size" }
  }
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: "t-1",
    name: "Lord Sterling Sterling-Hawke",
    role: "Bespoke Collection Collector, London",
    quote: "Aureum's Savile Row tailoring goes beyond clothing; it is sculptural heritage. The 24k gold pinstripes are incredibly fine, radiating under light in the most sophisticated manner. Outstanding.",
    image: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&q=80&w=300",
    rating: 5
  },
  {
    id: "t-2",
    name: "Dr. Marcello Rossi",
    role: "Haute Horology Enthusiast, Milan",
    quote: "The Swiss Caliber Tourbillon is an absolute masterwork. The integration of 18k gold mechanics and modern matte-black finishes is stunningly precise. I wore it to the Gala in Milan and received endless praise.",
    image: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&q=80&w=300",
    rating: 5
  },
  {
    id: "t-3",
    name: "Xavier Chevalier",
    role: "International Arts Curator, Paris",
    quote: "I travel four continents a year. The Grand Tourer Weekender is the absolute zenith of travel luggage. Supple box leather that develops a lovely gloss patina with every trip, accompanied by heavy durable gold hardware.",
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=300",
    rating: 5
  }
];

export const ATELIERS: AtelierLocation[] = [
  {
    id: "loc-1",
    city: "London Atelier & Showroom",
    address: "32B Savile Row, Mayfair, London W1S 3PT",
    phone: "+44 (0) 20 7946 0192",
    hours: "Mon - Sat: 10:00 AM - 7:00 PM, Sun: By Appointment Only",
    description: "Our historic flagship. Home to our master tailors and full bespoke tailoring commissions. Fully stocked with rare vintage Italian textile books."
  },
  {
    id: "loc-2",
    city: "Milan Salone Privé",
    address: "Via Montenapoleone, 14, 20121 Milano MI",
    phone: "+39 02 8374 9283",
    hours: "Tue - Sat: 11:00 AM - 8:00 PM, Mon: By Appointment Only",
    description: "A private penthouse overlooking Milan's fashion capital, offering our signature watch and leather goods lounge alongside styling experts."
  },
  {
    id: "loc-3",
    city: "Tokyo Club & Boutique",
    address: "5 Chome-11 Minami-Aoyama, Minato City, Tokyo 107-0062",
    phone: "+81 3-5573-0094",
    hours: "Daily: 11:00 AM - 9:00 PM",
    description: "A gorgeous brutalist architectural temple in Minami-Aoyama. Includes our ultra-exclusive Aureum Lounge serving Japanese whisky."
  }
];

export const QUIZ_QUESTIONS: QuizQuestion[] = [
  {
    id: 1,
    text: "Define your preferred stylistic aesthetic",
    options: [
      { label: "Bespoke tailoring", value: "formal", description: "Impeccably tailored suits, formal twilight tuxedos, structured cashmere double breasteds" },
      { label: "At-Ease Splendor", value: "casual", description: "Milanese soft velvet blazers, premium box-calf loafers, relaxed luxury outerwear" },
      { label: "The Collector's Aura", value: "watches", description: "Swiss tourbillon, complex heavy gilded chronometers, rare gemstone horology" }
    ]
  },
  {
    id: 2,
    text: "Which ambient scent profile resonates with your presence?",
    options: [
      { label: "Raw Saffron & Smoked Oud", value: "mysterious", description: "Dark, animalic, rich woody oriental notes that leave a lingering midnight shadow" },
      { label: "Gilded Amber & Cocoa Bark", value: "sensual", description: "Warm, sweet spices with deep cocoa, roasted espresso, and powdered vanilla beans" },
      { label: "Tuscan Bergamot & Cedarwood", value: "fresh", description: "Crisp Mediterranean citrus with dry smokey wood, fresh herbs, and leather" }
    ]
  },
  {
    id: 3,
    text: "What is the primary backdrop of your activities?",
    options: [
      { label: "High-Society Galas & Opera Houses", value: "gala", description: "Sartorial strict codes, red carpet appearances, historic auction salons" },
      { label: "Private Aviation & Superyacht Crossings", value: "travel", description: "Seamless global transit, bespoke weekender requirements, high-elevation style" },
      { label: "Executive Boardrooms & Elite Private Clubs", value: "boardroom", description: "Commanding authority, clean-cut structures, classic luxury statement pieces" }
    ]
  }
];

export const VIP_BENEFITS: VIPBenefit[] = [
  {
    id: "vip-1",
    title: "Atelier Priority Allocations",
    description: "Receive priority queue bookings for bespoke fittings with our Master Tailors and immediate white-glove notification for ultra-exclusive Swiss watch drops with production runs under 50 pieces globally."
  },
  {
    id: "vip-2",
    title: "Global Private Aviation Courier",
    description: "Your leather and timepiece purchases can be hand-delivered directly to your aircraft or luxury suite anywhere globally via unified bonded courier service."
  },
  {
    id: "vip-3",
    title: "Flagship Aureum Club Access",
    description: "Enjoy lifetime access to the private cigar lounges, whisky collections, and dynamic workspaces situated on upper floors of our London, Tokyo, and Milan boutiques."
  },
  {
    id: "vip-4",
    title: "Personal Styling Concierge",
    description: "A continuous 24/7 dedicated Whatsapp or Signal styling desk ready to curate capsule wardrobes, arrange fitting shipments, or coordinate formal attire for sudden public appearances."
  }
];
